# Generated by Django 5.1.7 on 2025-03-20 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEmp', models.CharField(max_length=200, verbose_name='Empresa')),
                ('giro', models.CharField(max_length=200, verbose_name='Giro')),
                ('direccionEmp', models.CharField(max_length=250, verbose_name='Dirección de la empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UniEconomicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Uni', models.CharField(max_length=200, null=True, verbose_name='ID Unidades economicas')),
                ('CleeUni', models.CharField(max_length=100, null=True, verbose_name='Clee')),
                ('Nombre_de_la_Unidad_Economica', models.CharField(max_length=250, null=True, verbose_name='Nombre de la unidad Economica')),
                ('Razon_social', models.CharField(max_length=250, null=True, verbose_name='Razón social')),
                ('Nombre_de_clase_de_la_actividad', models.CharField(max_length=250, null=True, verbose_name='Nombre de la clase de la actividad')),
                ('Descripcion_estrato_personal_ocupado', models.CharField(max_length=300, null=True, verbose_name='Descripcion del estrato')),
                ('Nombre_de_la_vialidad', models.CharField(max_length=250, null=True, verbose_name='Nombre de la vialidad')),
                ('Numero_exterior_o_kilometro', models.CharField(max_length=20, null=True, verbose_name='Numero exterior')),
                ('Letra_exterior', models.CharField(max_length=200, null=True, verbose_name='Letra exterior')),
                ('Nombre_de_asentamiento_humano', models.CharField(max_length=250, null=True, verbose_name='Asentamiento humano')),
                ('Codigo_postal', models.CharField(max_length=6, null=True, verbose_name='Codigo postal')),
                ('Entidad_federetiva', models.CharField(max_length=250, null=True, verbose_name='Estado')),
                ('Municipio', models.CharField(max_length=250, null=True, verbose_name='Municipio')),
                ('Localidad', models.CharField(max_length=250, null=True, verbose_name='Localidad')),
                ('Numero_de_telefono', models.CharField(max_length=13, null=True, verbose_name='Telefono')),
                ('Correo_electronico', models.CharField(max_length=250, null=True, verbose_name='Correo')),
                ('Sitio_en_Internet', models.CharField(max_length=250, null=True, verbose_name='Sitio web')),
                ('Latitud', models.CharField(max_length=200, null=True, verbose_name='Latitud')),
                ('Longitud', models.CharField(max_length=200, null=True, verbose_name='Longitud')),
                ('Fecha_de_incorporacion_al_denue', models.CharField(max_length=20, null=True, verbose_name='Fecha de incorporación al denue')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSuc', models.CharField(max_length=200, verbose_name='Sucursal')),
                ('direccionSuc', models.CharField(max_length=250, verbose_name='Dirección de la sucursal')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.empresa', verbose_name='Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomSuper', models.CharField(max_length=250, verbose_name='Supervisor')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.sucursal', verbose_name='Sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomAses', models.CharField(max_length=250, verbose_name='Asesor')),
                ('rutaAses', models.CharField(max_length=250, verbose_name='Ruta')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.supervisor', verbose_name='Supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_Cons', models.CharField(max_length=200, verbose_name='Consulta')),
                ('fecha_Cons', models.DateField(verbose_name='Fecha')),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.asesor', verbose_name='Asesor')),
                ('uniEc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.unieconomicas', verbose_name='Unidades Economicas')),
            ],
        ),
    ]
