# Generated by Django 5.1.7 on 2025-03-23 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_asesor_user_supervisor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unieconomicas',
            name='asesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='leads.asesor', verbose_name='Asesor'),
        ),
    ]
