# Generated by Django 5.1.7 on 2025-03-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_unieconomicas_asesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='unieconomicas',
            name='Status',
            field=models.CharField(choices=[('Prospecto', 'Prospecto'), ('Cliente Nuevo', 'Cliente Nuevo'), ('Ya Era Cliente', 'Ya Era Cliente'), ('Descartado', 'Descartado')], default='Prospecto', max_length=50),
        ),
    ]
