# Generated by Django 5.1.7 on 2025-03-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_unieconomicas_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='unieconomicas',
            name='FechaEdicion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
