# Generated by Django 5.1.7 on 2025-03-25 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_unieconomicas_fechaedicion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unieconomicas',
            old_name='Status',
            new_name='estado',
        ),
    ]
