# Generated by Django 5.1.7 on 2025-03-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_alter_unieconomicas_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unieconomicas',
            name='estado',
            field=models.CharField(choices=[('En atención', 'En atención'), ('Prospecto', 'Prospecto'), ('Cliente Nuevo', 'Cliente Nuevo'), ('Ya era Cliente', 'Ya era Cliente'), ('Descartado', 'Descartado')], default='En atención', max_length=50),
        ),
    ]
